from utilis.config import Config
# test tau and batchsizie

default_config = Config({
    "seed": 0,
    "tag": "default",
    "start_steps": 5000,
    "cuda": True,
    "num_steps": 1000001,
    "save": True,
    "save_interval_steps": 0,

    "eval": True,

    "eval_numsteps": 10000,
    "eval_interval_steps": 0,
    "eval_times": 5,
    "replay_size": 1000000,

    "algo": "FlowAC",
    "policy": "Flow",
    "steps": 1,
    "gamma": 0.99,
    "tau": 0.1,
    "lr": 0.0003, #0.0003
    "batch_size": 256,
    "updates_per_step": 1,
    "target_update_interval": 2, # for delayed policy update and target network update
    "hidden_size": 512,

    "safe_env": False,
    "cost_gamma": 0.97,
    "safe_threshold": 0.1,
    "safety_critic_mode": "cumulative",
    "qc_geom_mode": "max",
    "cdf_binarize_cost": True,
    "cdf_target_clip": True,
    "safe_bandwidth": 0.05,
    "lambda_safe": 1.0,
    "lambda_safe_schedule": False,
    "lambda_safe_start": 0.5,
    "lambda_safe_end": 0.8,
    "lambda_safe_warmup_steps": 30000,
    "lambda_safe_ramp_steps": 70000,
    "lambda_jvp": 0.05,
    "lambda_jvp_schedule": False,
    "lambda_jvp_start": 0.0,
    "lambda_jvp_end": 0.003,
    "lambda_jvp_warmup_steps": 30000,
    "lambda_jvp_ramp_steps": 70000,
    "jvp_warmup_steps": 20000,
    "jvp_mode": "grad",
    "normalize_jvp": False,
    "jvp_norm_mode": "exact",
    "jvp_hutchinson_samples": 1,
    "jvp_eps": 1e-6,
    "jvp_batch_size": 0,
    "jvp_sample_mode": "full",
    "jvp_update_interval": 1,
    "jvp_one_sided": False,
    "jvp_gate_mode": "boundary",
    "jvp_gate_temperature": 0.01,
    "soft_feasibility_gate": False,
    "feas_gate_tau": 0.05,
    "feas_gate_detach": True,
    "feas_gate_reward_floor": 0.2,
    "soft_normal_masking": False,
    "masking_warmup_steps": 20000,
    "mask_beta_max": 0.5,
    "mask_beta_tau": 10000,
    "mask_noise_scale": 0.01,
    "mask_noise_clip": 0.25,
    "directional_ref_noise": False,
    "directional_noise_mode": "none",
    "tangent_noise_scale": 0.05,
    "ref_noise_scale": 0.02,
    "normal_noise_scale": 0.01,
    "directional_noise_warmup_steps": 10000,
    "directional_noise_beta_max": 0.5,
    "directional_noise_eps": 1e-6,
    "directional_noise_clip": 0.3,
    "binary_cost": True,
    "safe_policy_loss": True,
    "diagnose_safety_geometry": False,
    "diagnose_safety_q_geometry": False,
    "diagnose_interval_steps": 1000,
    "safety_q_fd_eps": 0.01,
    "safety_q_boundary_width": 0.05,
    "high_fidelity_safety_q": False,
    "safety_q_priority": False,
    "safety_q_cost_weight": 2.0,
    "safety_q_boundary_weight": 3.0,
    "safety_q_td_weight": 0.0,
    "safety_q_max_weight": 5.0,
    "safety_q_extra_updates": 0,

    "target_kinetic_coef": 2.5,
    "init_log_alpha": -2.0,
    "auto_alpha": True,
    "compile_model": False,

    "normalize_obs": True,
    "obs_norm_clip": 10.0,
    "obs_norm_eps": 1e-8,

    "distributional_critic": False,
    "critic_num_atoms": 101,
    "critic_v_min": -10.0,
    "critic_v_max": 150.0,

})
