from utilis.config import Config


star_default_config = Config(
    {
        "method": "star",
        "task": "SafetyPointGoal1-v0",
        "tag": "default",
        "algo": "STAR",
        "seed": 0,
        "device": 0,
        "cuda": True,
        "safe_env": True,
        "normalize_obs": True,
        "obs_norm_clip": 10.0,
        "obs_norm_eps": 1e-8,
        "target_tau": 0.005,
        "target_update_interval": 1,
        "gamma": 0.99,
        "cost_gamma": 0.99,
        "actor_lr": 3e-4,
        "critic_lr": 3e-4,
        "cost_critic_lr": 3e-4,
        "alpha_lr": 3e-4,
        "lagrange_lr": 3e-4,
        "hidden_size": 256,
        "batch_size": 256,
        "replay_size": 1000000,
        "recent_fraction": 0.0,
        "start_steps": 5000,
        "num_steps": 1000000,
        "updates_per_step": 1,
        "policy_update_interval": 1,
        "cost_critic_mode": "reachability",
        "cost_critic_reduce": "max",
        "binary_cost": True,
        "env_cost_limit": 25.0,
        "star_risk_threshold": 0.10,
        "shadow_k": 16,
        "shadow_aggregation": "log_mean_exp",
        "shadow_temperature": 0.05,
        "shadow_local_std": 0.0,
        "shadow_beta_mode": "linspace",
        "shadow_reference_mode": "corridor",
        "shadow_chunk_size": 0,
        "star_lambda": 1.0,
        "star_kl_coef": 1.0,
        "star_kl_target": 0.01,
        "star_kl_mode": "hinge",
        "star_ref_update_interval": 20,
        "star_exec": True,
        "star_exec_candidates": 16,
        "star_exec_margin": 0.02,
        "star_exec_start_steps": 5000,
        "boundary_epsilon": 0.02,
        "eval": True,
        "eval_interval_steps": 10000,
        "eval_numsteps": 5000,
        "eval_times": 5,
        "save": True,
        "save_interval_steps": 0,
        "output_root": "results/star_aaai",
        "run_name": "",
        "ablation_group": "main",
        "ablation_name": "main",
        "metric_log_interval_steps": 1000,
    }
)
